In [1]:
import torch

In [2]:
import numpy as np

In [3]:
x=[[1,2],[3,4]]

### Create Tensors

In [4]:
x_tensor=torch.tensor(x)
x_tensor

tensor([[1, 2],
        [3, 4]])

In [5]:
x=np.array([[1,2],[3,4]])

In [6]:
tensor=torch.from_numpy(x)
tensor

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [7]:
x=torch.arange(25,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [8]:
x=torch.arange(25)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [9]:
torch.zeros(4,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [10]:
torch.ones(4,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# Tensor Attributes

In [11]:
x.shape

torch.Size([25])

In [12]:
x.dtype

torch.int64

In [13]:
x.device

device(type='cpu')

In [14]:
# Create 4 X 6 matrix

In [15]:
a=torch.randn(4,6)

In [16]:
b=torch.rand(4,6)

In [17]:
print(a)
print(b)

tensor([[-1.1824,  1.3755,  1.8175,  0.9843, -0.1525,  1.1158],
        [ 1.7545, -0.8837, -0.0737, -0.6097, -0.3553,  1.1356],
        [ 0.8707, -0.0894,  1.7369, -1.4336, -0.0812,  0.5224],
        [ 0.3802, -1.1845, -1.4001, -1.4508, -1.3760, -0.8578]])
tensor([[0.2020, 0.7559, 0.2944, 0.7059, 0.2256, 0.8867],
        [0.5069, 0.5571, 0.7163, 0.3244, 0.7916, 0.2096],
        [0.1007, 0.6395, 0.1805, 0.3626, 0.9752, 0.1704],
        [0.7679, 0.9510, 0.0066, 0.8095, 0.1425, 0.1450]])


In [18]:
#concatinate both tensor

In [19]:
big_tensor=torch.cat([a,b],dim=0)
print(big_tensor)

tensor([[-1.1824,  1.3755,  1.8175,  0.9843, -0.1525,  1.1158],
        [ 1.7545, -0.8837, -0.0737, -0.6097, -0.3553,  1.1356],
        [ 0.8707, -0.0894,  1.7369, -1.4336, -0.0812,  0.5224],
        [ 0.3802, -1.1845, -1.4001, -1.4508, -1.3760, -0.8578],
        [ 0.2020,  0.7559,  0.2944,  0.7059,  0.2256,  0.8867],
        [ 0.5069,  0.5571,  0.7163,  0.3244,  0.7916,  0.2096],
        [ 0.1007,  0.6395,  0.1805,  0.3626,  0.9752,  0.1704],
        [ 0.7679,  0.9510,  0.0066,  0.8095,  0.1425,  0.1450]])


In [20]:
# Add

In [21]:
c=a+b

In [22]:
c

tensor([[-0.9804,  2.1315,  2.1119,  1.6902,  0.0732,  2.0025],
        [ 2.2614, -0.3267,  0.6426, -0.2853,  0.4362,  1.3452],
        [ 0.9714,  0.5501,  1.9173, -1.0710,  0.8940,  0.6928],
        [ 1.1481, -0.2335, -1.3935, -0.6413, -1.2335, -0.7128]])

In [23]:
print(big_tensor.shape)

torch.Size([8, 6])


In [24]:
c.shape

torch.Size([4, 6])

In [25]:
torch.add(a,b)

tensor([[-0.9804,  2.1315,  2.1119,  1.6902,  0.0732,  2.0025],
        [ 2.2614, -0.3267,  0.6426, -0.2853,  0.4362,  1.3452],
        [ 0.9714,  0.5501,  1.9173, -1.0710,  0.8940,  0.6928],
        [ 1.1481, -0.2335, -1.3935, -0.6413, -1.2335, -0.7128]])

In [26]:
e=a*b
print(e)

tensor([[-0.2388,  1.0398,  0.5350,  0.6948, -0.0344,  0.9894],
        [ 0.8894, -0.4923, -0.0528, -0.1978, -0.2813,  0.2380],
        [ 0.0877, -0.0572,  0.3134, -0.5199, -0.0791,  0.0890],
        [ 0.2920, -1.1265, -0.0092, -1.1744, -0.1961, -0.1244]])


In [27]:
c

tensor([[-0.9804,  2.1315,  2.1119,  1.6902,  0.0732,  2.0025],
        [ 2.2614, -0.3267,  0.6426, -0.2853,  0.4362,  1.3452],
        [ 0.9714,  0.5501,  1.9173, -1.0710,  0.8940,  0.6928],
        [ 1.1481, -0.2335, -1.3935, -0.6413, -1.2335, -0.7128]])

In [28]:
c.view(8,3)

tensor([[-0.9804,  2.1315,  2.1119],
        [ 1.6902,  0.0732,  2.0025],
        [ 2.2614, -0.3267,  0.6426],
        [-0.2853,  0.4362,  1.3452],
        [ 0.9714,  0.5501,  1.9173],
        [-1.0710,  0.8940,  0.6928],
        [ 1.1481, -0.2335, -1.3935],
        [-0.6413, -1.2335, -0.7128]])

In [29]:
# view can change the size of matrix

In [30]:
c.view(12,2)

tensor([[-0.9804,  2.1315],
        [ 2.1119,  1.6902],
        [ 0.0732,  2.0025],
        [ 2.2614, -0.3267],
        [ 0.6426, -0.2853],
        [ 0.4362,  1.3452],
        [ 0.9714,  0.5501],
        [ 1.9173, -1.0710],
        [ 0.8940,  0.6928],
        [ 1.1481, -0.2335],
        [-1.3935, -0.6413],
        [-1.2335, -0.7128]])

In [31]:
# also can be done by reshape function